FEAT : BDBD-345 Firebase 휴대폰 인증 제작
FakeDevelopers/BidderBidder_IOS pull request #10
Opened 2022-07-14 04:34 UTC by SungHyunC

### 개요
- Firebase 휴대폰 인증 제작
### 변경사항
- Firebase 연결 및 .gitignore 내용 추가
### 관련 지라 및 위키 링크
- [BDBD-345](https://fake-developers.atlassian.net/jira/software/projects/BDBD/boards/10?selectedIssue=BDBD-345)
### 리뷰어에게 하고 싶은 말
- Firebase 휴대폰 인증 할 수 있게 만들었습니다.
- .gitignore 내용 추가했습니다

2022-07-14 05:04 UTC, minseonglove reviewed
Auth에 languageCode를 설정하는 부분이 없는데 인증 문자가 한글로 잘 받아와 지니

2022-07-14 05:04 UTC, minseonglove commented on BidderBidder/Info.plist
> +			</array>
이건 보여도 괜찮나

2022-07-14 05:04 UTC, minseonglove commented on BidderBidder/LoginViewController.swift
> +            print("\(authResult!)")
error에 걸리면 이 코드는 실행이 안되는거야?

2022-07-14 06:07 UTC, SungHyunC commented on BidderBidder/Info.plist
> +			</array>
.gitignore를 잘못 올려서 다시 올려놓았는데 그전꺼라 아마 올라온것같아요

2022-07-14 06:08 UTC, SungHyunC commented on BidderBidder/LoginViewController.swift
> +            print("\(authResult!)")
오 이건 수정해야될것같네요

2022-07-14 06:33 UTC, Dorii0513 reviewed
성현님 고생하셨습니다 👍

2022-07-14 11:56 UTC, konempty requested changes
고생하셨습니다 조금만더 수고부탁드릴게요 ㅎㅎ

2022-07-14 11:56 UTC, konempty commented on .gitignore
> -# Created by https://www.toptal.com/developers/gitignore/api/macos,swift,xcode
헛.. 깃이그노어 작성하실때 macos를 빼먹으셨군요.. 그것도 추가해주시는게 좋을것 같아요!

2022-07-14 11:56 UTC, konempty commented on BidderBidder/Info.plist
> +			</array>
깃이그노어를 새로 설정하셨으면 스테이징을 정리해주셔야 해요
https://www.daleseo.com/gitignore/ 여기 주의사항부분을 보시면 좋을것 같네요 ㅎㅎ

2022-07-14 11:56 UTC, konempty commented
> Kudos, SonarCloud Quality Gate passed!    [![Quality Gate passed](https://camo.githubusercontent.com/e4a90cf346b46d44c5652111d68603714bfb7693043d07a95992de3a30bfce04/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f7061737365642d313670782e706e67)](https://sonarcloud.io/dashboard?id=FakeDevelopers_BidderBidder_IOS&pullRequest=10)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=10&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=10&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=10&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=10&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=10&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=10&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=FakeDevelopers_BidderBidder_IOS&pullRequest=10&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=FakeDevelopers_BidderBidder_IOS&pullRequest=10&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=FakeDevelopers_BidderBidder_IOS&pullRequest=10&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=10&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=10&resolved=false&types=CODE_SMELL) [1 Code Smell](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=10&resolved=false&types=CODE_SMELL)
> 
> [![No Coverage information](https://camo.githubusercontent.com/86785eaa572e061f5ecb3f8bf1cbb7b8eca44925083f92d067805b4362cead0c/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f4e6f436f766572616765496e666f2d313670782e706e67)](https://sonarcloud.io/component_measures?id=FakeDevelopers_BidderBidder_IOS&pullRequest=10) No Coverage information [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=FakeDevelopers_BidderBidder_IOS&pullRequest=10&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=FakeDevelopers_BidderBidder_IOS&pullRequest=10&metric=new_duplicated_lines_density&view=list)

앗 코드스멜이!!

2022-07-14 12:11 UTC, Dorii0513 approved these changes
코멘트로 잘못 남겨서 다시 리뷰 남깁니다! 고생하셨어요 성현님🙂

2022-07-14 12:29 UTC, minseonglove approved these changes
![yQoeObI](https://user-images.githubusercontent.com/90435036/178982487-1374fa5f-6536-4be4-83c7-45dc2137674a.gif)

2022-07-15 01:24 UTC, SungHyunC commented on .gitignore
> -# Created by https://www.toptal.com/developers/gitignore/api/macos,swift,xcode
넵!

2022-07-15 02:29 UTC, minseonglove requested changes
![s02-11](https://user-images.githubusercontent.com/90435036/179134861-819a08d2-1cc5-4899-8b0e-a9b7c93d68b7.gif)
Info파일은 숨기십시오

2022-07-15 02:29 UTC, minseonglove commented on BidderBidder/LoginViewController.swift
> +        Auth.auth().languageCode = "kr"
우리는 한국 사람들을 타겟으로 하고 있긴하지만
사용자에게 맞는 국가코드를 넣어주는 것이 앱 표준이야

2022-07-15 02:29 UTC, minseonglove commented on BidderBidder/LoginViewController.swift
> +        else if limitTime == 0 {
else로 하는것이 더 이쁠지도

2022-07-15 02:29 UTC, minseonglove commented on BidderBidder/Info.plist
> +			</array>
없어질 때까지 숨참음

2022-07-15 10:29 UTC, konempty approved these changes
고생하셨습니다 👍

2022-07-15 16:24 UTC, minseonglove approved these changes
헉 승인하는걸 잊고있었네

2022-07-15 16:47 UTC, merged