FEAT : BDBD-393 IOS 검색화면 개발
FakeDevelopers/BidderBidder_IOS pull request #21
Opened 2022-09-13 04:58 UTC by SungHyunC

### 개요
 - IOS 검색화면 개발
### 변경사항
 - 검색화면을 개발했습니다.
### 관련 지라 및 위키 링크
 - [지라](https://fake-developers.atlassian.net/jira/software/projects/BDBD/boards/10?selectedIssue=BDBD-393)
### 리뷰어에게 하고 싶은 말
 - 오래 걸렸습니다.. 이상한부분은 바로 지적해주세요!

2022-09-13 14:26 UTC, konempty approved these changes
크흐 정말 오랬동안 고생 하셨어요! 리뷰 확인 부탁드릴게요

2022-09-13 14:26 UTC, konempty commented on BidderBidder/Controller/SearchViewController.swift
> +        let searchBar = UISearchBar(frame: CGRect(x: 0, y: 0, width: width - 28, height: 0))
오호라 28이라는 숫자는 어떤 의미인가요? 매직 넘버면은 좀더 적당한 내용으로 바꿔주세요!

2022-09-13 14:26 UTC, konempty commented on BidderBidder/Controller/TagCollectionViewController.swift
> +            UserDefaults.standard.removeObject(forKey: "searchHistory")
포문안돌리고 UserDefaults.standard.removeObject(forKey: "searchHistory") 요거 한번만 실행하는것만으로는 안되나요?

2022-09-13 14:26 UTC, konempty commented on BidderBidder/Controller/SearchViewController.swift
> +        tableView.isHidden = true
요건 약간 개취이긴 한데 저는 주로 요런 설정은 스토리보드에서 하는걸 선호하는데 성현씨는 코드로 쓰는 방식을 선호하시나요?
혹시 코드로 쓰면 어떤 장점이 있는지 궁금하네요!

2022-09-13 14:26 UTC, konempty commented on BidderBidder/Controller/SearchViewController.swift
> +                if dj.lowercased().contains(searchText.lowercased()) {
오.. dj라는건 무슨 의미 인지 감이 안오는데 직관적인 이름으로 변경하면 어떨까요?

2022-09-13 14:26 UTC, konempty commented on BidderBidder/Controller/TagCollectionViewController.swift
> +                self.dataArray.remove(at: indexPath.row)
각 셀마다 변하는건 겨우 indexPath.row 요거 하나 일것 같은데 delete라는 클로져를 매번 생성하는것 보단 공통로직을 셀안에 넣어두고 셀에는 indexPath.row 요것만 전달해주면 어떨까요?

2022-09-13 14:26 UTC, konempty commented on BidderBidder/Info.plist
> -	<string>갤러리 사용 권한을 허용해주세요</string>
오호... 이건 의도적으로 삭제하신걸까요? 그렇다면 이유가 궁금합니다!

2022-09-13 14:26 UTC, konempty commented on BidderBidder/Controller/TagCollectionViewController.swift
> +        let cellHeight = (height - heightPadding) / itemsPerColumn
혹시나 해서 묻는데 요 함수는 단한번만 실행되는 함수 맞을까요?

2022-09-13 14:26 UTC, konempty commented on BidderBidder/Controller/SearchViewController.swift
> +        print(childVC?.dataArray)
앗 ㅋㅋㅋ 디버깅용 프린트 문은 없애주세요!

2022-09-13 14:26 UTC, konempty commented on BidderBidder/Controller/SearchViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: cellIdentifier, for: indexPath) as UITableViewCell
오호라 요건 단한번 사용되는데 변수화 하셨는데 아래의 UIImage의 경우는 문자열을 그대로 넣으셨네요? 요건 통일 해주시면 어떨까요?

2022-09-13 14:26 UTC, konempty commented on BidderBidder/Cell/TagCollectionViewCell.swift
> +            print("ERROR")
요것도 없애주시는게 좋을듯 하네요 ㅋㅋㅋ

2022-09-13 14:26 UTC, konempty commented on BidderBidder/Controller/TagCollectionViewController.swift
> +class TagCollectionViewController: UIViewController {
<img width="313" alt="스크린샷 2022-09-13 오후 11 17 03" src="https://user-images.githubusercontent.com/44064530/189925378-f269c5ae-eb80-4822-982e-2ffaa96a7e4e.png">
중복된 내용은 없어져야 하지 않을까요?

2022-09-13 14:26 UTC, konempty commented on BidderBidder/Controller/TagCollectionViewController.swift
> +class TagCollectionViewController: UIViewController {
그리고 인기검색어의 아이템이 클릭되면 해당 내용으로 바로 검색되는 기능도 추가되었다면 어떨까요?

2022-09-13 14:26 UTC, konempty commented on BidderBidder/SupportingFile/Model.swift
> +            tags.append(Tag(name: name))
참고로 요 코드는 
```
var tags: [Tag] =  ["Design", "Research", "Beauty", "Travel", "Makeup"].map({ name in
            return Tag(name: name)
        }
    )
```
요렇게도 줄여서 쓸수 있어요!

2022-09-13 14:28 UTC, konempty commented
아앗.. 린트랑 코드스멜도 수정 부탁드릴게요!

2022-09-13 14:37 UTC, konempty commented on BidderBidder/Controller/TagCollectionViewController.swift
> +            let cellA = collectionView.dequeueReusableCell(withReuseIdentifier: "RecentlySearchViewCell", for: indexPath) as! RecentlySearchViewCell
변수 명을 cellA로 지으신 이유가 있으신가요?

2022-09-13 16:30 UTC, minseonglove approved these changes
![yQoeObI](https://user-images.githubusercontent.com/90435036/189956269-2aad3e97-31f5-4414-b71d-cc62c83f5860.gif)
1. 화살표가 사이즈별로 3개가 있던데 벡터를 고려해보던가 큰 화살표 이미지 하나를 화면 크기에 맞게 줄여쓰는 방법을 고려해 보십시유
2. 커밋 하나에 변경된 코드가 너무 많아 다음 작업 부터는 기능 단위로 분리해서 커밋해줘

2022-09-13 16:30 UTC, minseonglove commented on BidderBidder/Cell/TagCollectionViewCell.swift
> +            print("ERROR")
나중에라도 에러를 표시해줘야하는 상황이 생기면 ERROR 보다는 이게 어떤 상황에서 발생하는 에러인지 명확하게 표시해줘

2022-09-13 16:30 UTC, minseonglove commented on BidderBidder/Controller/SearchViewController.swift
> +        if let data = UserDefaults.standard.object(forKey: "searchHistory") as? [String] {
searchHistory 키 값이 여러곳에서 쓰이는데 이럴 땐 상수로 관리하는게 편해

2022-09-13 16:30 UTC, minseonglove commented on BidderBidder/Controller/SearchViewController.swift
> +    }
와 이건 뭐지

2022-09-13 16:30 UTC, minseonglove commented on BidderBidder/Controller/TagCollectionViewController.swift
> +        return tags.count
삼항 연산자를 리턴하면 기가 맥히겠다

2022-09-13 16:30 UTC, minseonglove commented on BidderBidder/Controller/SearchViewController.swift
> +                if dj.lowercased().contains(searchText.lowercased()) {
이 메소드는 코드 자체를 축약 할 수 있어 뵈는군

2022-09-13 16:30 UTC, minseonglove commented on BidderBidder/Controller/SearchViewController.swift
> +        filteredArr = []
배열 변수명으로 Array와 Arr가 둘 다 존재하네
되도록이면 하나로 통일하는게 이뻐

2022-09-13 16:30 UTC, minseonglove commented on BidderBidder/Controller/SearchViewController.swift
> +    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
메소드 명이 정해진 규칙을 따르고 있는거 같아서 보기 좋네

2022-09-13 16:30 UTC, minseonglove commented on BidderBidder/Controller/TagCollectionViewController.swift
> +            cell.tags = tag
tag가 오로지 cell.tags에 tags[indexPath.item]를 할당하기 위한 목적으로 선언됐는데
tags[indexPath.item] 이게 딱히 길지도 않아서 cell.tags에 직접 할당하는게 더 이뻐보여

2022-09-13 16:30 UTC, minseonglove commented on BidderBidder/SupportingFile/Model.swift
> +        return tags
shuffled를 써보는건 어때

2022-09-13 16:30 UTC, minseonglove commented on BidderBidder/SupportingFile/UIView.swift
> +    func makeRoundedWithBorder(radius: CGFloat, color: CGColor) {
borderWidth도 매개변수로 받으면 재사용성이 높아질테야

2022-09-13 23:40 UTC, konempty reviewed
.DS_Store 파일은 깃이그노어에 추가됐을텐데 올리신 이유가 있는걸까요?

2022-09-14 02:39 UTC, SungHyunC commented on BidderBidder/Controller/SearchViewController.swift
> +        let searchBar = UISearchBar(frame: CGRect(x: 0, y: 0, width: width - 28, height: 0))
알겠습니다!

2022-09-14 02:40 UTC, SungHyunC commented on BidderBidder/Controller/TagCollectionViewController.swift
> +            UserDefaults.standard.removeObject(forKey: "searchHistory")
가능합니다! 변경해놓겠습니다

2022-09-14 02:45 UTC, SungHyunC commented on BidderBidder/Controller/SearchViewController.swift
> +                if dj.lowercased().contains(searchText.lowercased()) {
블로그 참고 하고 따로 못 바꿨네요 바꿔놓겠습니다

2022-09-14 02:45 UTC, SungHyunC commented on BidderBidder/Info.plist
> -	<string>갤러리 사용 권한을 허용해주세요</string>
pull 하는 과정에서 제대로 안불러와져서 없어졌나보네요 다시 해놓겠습니다

2022-09-14 02:46 UTC, SungHyunC commented on BidderBidder/Controller/SearchViewController.swift
> +        print(childVC?.dataArray)
넵!

2022-09-14 02:46 UTC, SungHyunC commented on BidderBidder/Cell/TagCollectionViewCell.swift
> +            print("ERROR")
[konempty]: 알겠습니다! / [minseonglove]: 정확하게 표시해놓겠습니다

2022-09-14 04:03 UTC, SungHyunC commented on BidderBidder/Controller/SearchViewController.swift
> +        tableView.isHidden = true
만들때 다른걸 참고하면서 만들어가지고 tableView.delegate = self , tableView.dataSource = self 이부분은 잘모르겠는데
tableView.isHidden = true 여기 이거는 필요해서 해놓았습니다

2022-09-14 04:20 UTC, konempty commented on BidderBidder/Controller/SearchViewController.swift
> +        tableView.isHidden = true
아하 참고해서 개발하시는건 좋은데 코드의 의미를 모르고 그냥 가져다 쓰는건 좋지않아요 ㅠㅠ
그리고 tableView.isHidden = true 요것도 스토리 보드에서 설정할수 있을것 같아요!

2022-09-14 05:06 UTC, SungHyunC commented on BidderBidder/Controller/TagCollectionViewController.swift
> +        let cellHeight = (height - heightPadding) / itemsPerColumn
디버깅해봤는데 아닌것같네요 검색할때 여러번 실행시키네요

2022-09-14 05:08 UTC, SungHyunC commented on BidderBidder/SupportingFile/Model.swift
> +            tags.append(Tag(name: name))
오호 알려주셔서 감사합니다

2022-09-14 05:10 UTC, SungHyunC commented on BidderBidder/Controller/TagCollectionViewController.swift
> +            let cellA = collectionView.dequeueReusableCell(withReuseIdentifier: "RecentlySearchViewCell", for: indexPath) as! RecentlySearchViewCell
한화면에 콜렉션뷰를 두개 동시에 쓰니 기능들이 같이 써지더라구요 그래서 cellA로 나누어서 구별해놓았습니다.
아래껀 그럼 cellB로 구별해둘까요?

2022-09-14 05:16 UTC, konempty commented on BidderBidder/Controller/TagCollectionViewController.swift
> +        let cellHeight = (height - heightPadding) / itemsPerColumn
그렇다면 여기에 있는 코드들은 매 실행마다 값을 변화가 없을것 같은데 별도의 상수나 변수나 빼낼순 없을까요?

2022-09-14 05:18 UTC, konempty commented on BidderBidder/Controller/TagCollectionViewController.swift
> +            let cellA = collectionView.dequeueReusableCell(withReuseIdentifier: "RecentlySearchViewCell", for: indexPath) as! RecentlySearchViewCell
a,b는 직관적이지 않으니까
recentlyCollecrionCell처럼 직관적으로 하면 어떨까요?

2022-09-14 05:23 UTC, SungHyunC commented on BidderBidder/Controller/SearchViewController.swift
> +    }
이 방법을 구현하지 않으면 테이블은 1개의 섹션으로 구성됩니다. 라고 문서에 나와있네요
지우겠습니다

2022-09-15 15:28 UTC, Dorii0513 commented on BidderBidder/Controller/SearchViewController.swift
> +        let searchBar = UISearchBar(frame: CGRect(x: 0, y: 0, width: width - 28, height: 0))
UI 부분 setup 하는 메소드를 따로 만들어 관리하는군요!
이렇게 setup 부분을 따로 설정하는 이유가 초기화된 화면 세팅을 위해서 인가요??

2022-09-15 15:30 UTC, Dorii0513 approved these changes
성현님 고생 많으셨습니다!👍👍

2022-09-15 15:31 UTC, Dorii0513 commented on BidderBidder/Controller/SearchViewController.swift
> +        let searchBar = UISearchBar(frame: CGRect(x: 0, y: 0, width: width - 28, height: 0))
UI 부분 setup 하는 메소드를 따로 만들어 관리하는군요!
이렇게 setup 부분을 따로 설정하는 이유가 초기화된 화면 세팅을 위해서 인가요??

2022-09-23 00:48 UTC, SungHyunC commented on BidderBidder/Controller/SearchViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: cellIdentifier, for: indexPath) as UITableViewCell
알겠습니다!

2022-09-23 00:54 UTC, SungHyunC commented on BidderBidder/Controller/SearchViewController.swift
> +        let searchBar = UISearchBar(frame: CGRect(x: 0, y: 0, width: width - 28, height: 0))
맞습니다! 그리고 조금 더 깔끔하게 하기 위해서 해놓았습니다

2022-10-05 12:03 UTC, konempty approved these changes
고생하셨습니다! 리뷰 확인 부탁드릴게요!

2022-10-05 12:03 UTC, konempty commented on BidderBidder/Cell/RecentlySearchViewCell.swift
> +        parentVC.dataArr.remove(at: index)
톡으로도 말씀드렸던것 같은데 history 대신에 아래의 코드가 더 낫지 않나요?
parentVC.dataArr.remove(at: index)
 UserDefaults.standard.set( parentVC.dataArr, forKey: Constant.searchHistory)

2022-10-05 12:03 UTC, konempty commented on BidderBidder/Cell/TagCollectionViewCell.swift
> +            print("ERROR")
요건 아직 안없어 진건가요??

2022-10-05 12:03 UTC, konempty commented on BidderBidder/Controller/SearchViewController.swift
> +    var arr = [String]()
흠... 이건 어디서 사용되는것인지 변수명을 명확히 지어주세요!

2022-10-05 12:03 UTC, konempty commented on BidderBidder/Controller/SearchViewController.swift
> +        tableView.isHidden = true
요것도 반영 안하시는걸로 결정하신걸까요?

2022-10-05 12:03 UTC, konempty commented on BidderBidder/Controller/SearchViewController.swift
> +            for arrList in childVC?.dataArr ?? [] {
arrList 라는 이름음 좋아보이지 않네요 ㅠㅠ

2022-10-05 12:03 UTC, konempty commented on BidderBidder/Controller/TagCollectionViewController.swift
> +        recentlyCollectionView.dataSource = self
dataSoure는 스토리보드상에서 설정하는건 어떨까요?

2022-10-05 12:03 UTC, konempty commented on BidderBidder/Controller/TagCollectionViewController.swift
> +        let cellHeight = (height - heightPadding) / itemsPerColumn
요것도 리뷰 반영이 안되는걸까요?

2022-10-05 12:03 UTC, konempty commented on BidderBidder/Controller/SearchViewController.swift
> +        backButton.title = ""
뒤로가기 버튼을 동적으로 생성하시는 이유가 궁금합니다!

2022-10-05 12:25 UTC, minseonglove requested changes
실패했을 때 터지는 코드는 되도록 자제 해야해
변수명도 당장의 연산에 쓰고 버리는 임시 변수 같은 느낌이 아니라면 얘가 하는 일을 어느정도 유추할 수 있도록 이름을 지어줘야해

딱 한 번만 더 수정해보자

2022-10-05 12:25 UTC, minseonglove commented on BidderBidder/Cell/RecentlySearchViewCell.swift
> +    private lazy var collectionView = (superview as! UICollectionView)
확신에 찼어도 실패 시 폭발하는 코드는 가능한 자제해야해

2022-10-05 12:25 UTC, minseonglove commented on BidderBidder/Cell/RecentlySearchViewCell.swift
> +    private var index: Int!
변수명이 추상적이야 뭘 위한 인덱스인지 명시할 필요가 있겠어

2022-10-05 12:25 UTC, minseonglove commented on BidderBidder/Cell/TagCollectionViewCell.swift
> +            print("ERROR")
이거 그대로야..!

2022-10-05 12:25 UTC, minseonglove commented on BidderBidder/Controller/SearchViewController.swift
> +    lazy var childVC = children.first as? TagCollectionViewController
여긴 캐스팅 이쁘게 잘했네

2022-10-05 12:25 UTC, minseonglove commented on BidderBidder/Controller/SearchViewController.swift
> +            let indexNum = dataArr.firstIndex(of: input)
contains를 쓴다음에 firstIndex를 또 쓰는건 효율이 나빠
firstIndex만 쓰는쪽으로 개선해 보자

2022-10-05 12:25 UTC, minseonglove commented on BidderBidder/Controller/SearchViewController.swift
> +            childVC?.recentlyCollectionView.reloadData()
if든 else든 수행되는 동작이라면 밖으로 빼는게 맞는 것이야

2022-10-05 12:25 UTC, minseonglove commented on BidderBidder/Controller/SearchViewController.swift
> +            childVC?.dataArr = data
다른 뷰 컨트롤러의 값을 직접 조작하는게 쪼끔 뭐시기하네

2022-10-05 12:25 UTC, minseonglove commented on BidderBidder/SupportingFile/Model.swift
> +        let randTags = tags.shuffled()
shuffled 자체를 리턴하면 을마나 이쁘니

2022-10-05 12:44 UTC, konempty reviewed
<img width="323" alt="스크린샷 2022-10-05 오후 9 44 04" src="https://user-images.githubusercontent.com/44064530/194063115-7ed5c35b-42a7-4f18-a046-322e8e232fa5.png">
절대 죽지않는 좀비 인가요? ㅋㅋㅋㅋ DS_Store 왜 살아났죠

2022-10-06 11:28 UTC, SungHyunC commented on BidderBidder/Controller/TagCollectionViewController.swift
> +        recentlyCollectionView.dataSource = self
방법을 몰라가지고 못했었는데 찾아서 해놓았습니다!

2022-10-06 11:29 UTC, SungHyunC commented on BidderBidder/Controller/SearchViewController.swift
> +            for arrList in childVC?.dataArr ?? [] {
바꿔놓았습니다!

2022-10-06 11:29 UTC, SungHyunC commented on BidderBidder/Controller/SearchViewController.swift
> +    var arr = [String]()
테스트용인데 삭제를 못했네요

2022-10-06 11:30 UTC, SungHyunC commented on BidderBidder/Cell/RecentlySearchViewCell.swift
> +        parentVC.dataArr.remove(at: index)
이렇게 안하면 기능이 제대로 작동을 안하더라구요 삭제를 해도 그대로 있네요

2022-10-06 11:33 UTC, SungHyunC commented on BidderBidder/Controller/SearchViewController.swift
> +        backButton.title = ""
네비게이션 화면에서 뒤로가기 버튼이 안생겨서 만들어 뒀던걸 아직 냅두고있었네요 삭제했습니다

2022-10-06 11:46 UTC, SungHyunC commented on BidderBidder/Cell/RecentlySearchViewCell.swift
> +    private var index: Int!
넵!

2022-10-06 12:37 UTC, SungHyunC commented on BidderBidder/Controller/SearchViewController.swift
> +            let indexNum = dataArr.firstIndex(of: input)
해결했습니다

2022-10-06 12:37 UTC, SungHyunC commented on BidderBidder/Controller/SearchViewController.swift
> +    lazy var childVC = children.first as? TagCollectionViewController
굳굳

2022-10-06 12:42 UTC, SungHyunC commented on BidderBidder/Controller/SearchViewController.swift
> +            childVC?.dataArr = data
TagCollectionViewController에다가 옮겨놓았습니다

2022-10-06 12:42 UTC, SungHyunC commented on BidderBidder/SupportingFile/Model.swift
> +        let randTags = tags.shuffled()
최고입니다

2022-10-06 12:48 UTC, SungHyunC commented on BidderBidder/Controller/SearchViewController.swift
> +            childVC?.recentlyCollectionView.reloadData()
이부분에 대해서는 잘 모르겠습니다

2022-10-07 00:20 UTC, SungHyunC commented on BidderBidder/Cell/TagCollectionViewCell.swift
> +            print("ERROR")
삭제했습니다!

2022-10-07 00:54 UTC, konempty reviewed
<img width="1395" alt="스크린샷 2022-10-07 오전 9 52 09" src="https://user-images.githubusercontent.com/44064530/194443671-ebf8045a-2122-441b-a12f-f06e483e5ad7.png">
헐ㄹㄹㄹ 이거 필요없는 파일일거예요 없애주세요

2022-10-07 01:42 UTC, SungHyunC commented on BidderBidder/Controller/TagCollectionViewController.swift
> +                self.dataArray.remove(at: indexPath.row)
해결됬습니다

2022-10-07 01:42 UTC, SungHyunC commented on BidderBidder/Controller/SearchViewController.swift
> +        tableView.isHidden = true
스토리보드상에서 설정해보겠습니다

2022-10-07 02:13 UTC, SungHyunC commented on BidderBidder/Controller/TagCollectionViewController.swift
> +        let cellHeight = (height - heightPadding) / itemsPerColumn
@뺄수 있었던게 2개밖에 없어서 나머지는 어떻게해야될까요?

2022-10-07 02:13 UTC, SungHyunC commented on BidderBidder/SupportingFile/Model.swift
> +        let randTags = tags.shuffled()
바로 바꿨습니다!

2022-10-07 10:20 UTC, konempty approved these changes
고생하셨습니다 👍

2022-10-07 10:20 UTC, konempty commented on BidderBidder/Cell/TagCollectionViewCell.swift
> +    func update() {
요 메소드 다른곳에서 사용 안되는것 같은데 굳이 메소드로 존재할 필요가 있을까여?

2022-10-07 10:20 UTC, konempty commented on BidderBidder/Controller/MainViewController.swift
> +        super.viewWillAppear(animated)
요건 필요 할까요?

2022-10-07 10:20 UTC, konempty commented on BidderBidder/Controller/TagCollectionViewController.swift
> +        let cellHeight = (height - heightPadding) / itemsPerColumn
이거 더뺄수있어요!

2022-10-07 13:28 UTC, Dorii0513 approved these changes
성현님 고생하셨습니다! 코드 깔끔하고 좋은것 같아요 👍

2022-10-08 02:56 UTC, SungHyunC commented on BidderBidder/Cell/TagCollectionViewCell.swift
> +    func update() {
없애두도록하겠습니다!

2022-10-08 02:58 UTC, SungHyunC commented on BidderBidder/Controller/MainViewController.swift
> +        super.viewWillAppear(animated)
tabBar부분을 나타나게 해줄려고해서 필요합니다!

2022-10-08 06:35 UTC, minseonglove approved these changes
![yQoeObI](https://user-images.githubusercontent.com/90435036/194693536-683de122-f5d5-4d81-bf17-4e644b39ce0f.gif)
멋지지 않니

2022-10-08 06:35 UTC, minseonglove commented on BidderBidder/Controller/MainViewController.swift
> +            let productViewController = segue.destination as! ProductDetailViewController
스위프트는 어떻게 동작하는지 모르겠는데
is로 segue.destination 타입 검사를 했어도 안에서 as로 강제 형변환 하는 과정이 필요하니

2022-10-08 07:07 UTC, SungHyunC commented on BidderBidder/Controller/MainViewController.swift
> +            let productViewController = segue.destination as! ProductDetailViewController
이 부분은 제가 담당한게 아니라서 잘 모르겠습니닷

2022-10-08 07:23 UTC, merged