FEAT : BDBD-210 UI 변경
FakeDevelopers/BidderBidder_IOS pull request #6
Opened 2022-05-12 04:20 UTC by SungHyunC

### 개요
UI 변경
### 변경사항
로딩화면 추가, 계정 입력 및 로그인 화면 UI 변경
### 관련 지라 및 위키 링크
[BDBD-210](https://fake-developers.atlassian.net/jira/software/projects/BDBD/boards/10?selectedIssue=BDBD-210)
### 리뷰어에게 하고 싶은 말
얼른 UI마저 만들고 기능만들겠습니다! underline pod으로 가져와서 한번 써보았습니다. 어떤가요?

2022-05-12 04:56 UTC, minseonglove reviewed
엗헴

2022-05-12 04:56 UTC, minseonglove commented on BidderBidder/LoginViewController.swift
> +        self.layer.backgroundColor = UIColor(rgb: 0x21CEFF).cgColor
0x21CEFF 이걸 어디에 상수로 지정해 둘 수 있나
나중에 컬러에 변경이 생기면 수정이 쉽지 않을 것 같아

2022-05-12 12:07 UTC, konempty commented
<img width="437" alt="스크린샷 2022-05-12 오후 9 06 18" src="https://user-images.githubusercontent.com/44064530/168071030-359e9168-02f3-4614-8ccb-7b09c6630269.png">
일단 49개의 워닝이 있네요! 되도록이면 전부 수정해주세요!

2022-05-12 12:16 UTC, konempty requested changes
수정된 파일이 117개나 있어서 순간 식겁했네요ㅋㅋㅋㅋ 조금만 더 고치시면 좋을것 같아요! 👍

2022-05-12 12:16 UTC, konempty commented on Podfile
> +  pod 'SnapKit'
이건 약간 취향차이인데 코코아 팟 보다는 SPM을 쓰는게 좀더 애플이 지원해주는 방식이니까 SPM을 사용하시면 좋을것 같아요!

2022-05-12 12:16 UTC, konempty commented on Pods/SnapKit/Source/Constraint.swift
> +public final class Constraint {
오.. Pod가 다운로드 한 파일은 깃에 올리지 않는게 좋아요 깃이그노어에 pod하위 디렉토리 설정해주세요!

2022-05-12 12:16 UTC, konempty commented on BidderBidder/LoginViewController.swift
> +   convenience init(red: Int, green: Int, blue: Int) {
저 약간 궁금한건데 int대신에 uint8로 하면 아래의 어썰션은 필요없어지지 않을까요?

2022-05-12 12:16 UTC, konempty commented on BidderBidder/LoginViewController.swift
>          //Navigation Bar 숨기기
주석을 달때는 //와 글자사이에는 스페이스가 1칸 들어가야 해요
"// 이렇게요"

2022-05-12 12:57 UTC, minseonglove commented
> <img alt="스크린샷 2022-05-12 오후 9 06 18" width="437" src="https://user-images.githubusercontent.com/44064530/168071030-359e9168-02f3-4614-8ccb-7b09c6630269.png">
> 
> 일단 49개의 워닝이 있네요! 되도록이면 전부 수정해주세요!

이게 다 무슨 냄새야

> Kudos, SonarCloud Quality Gate passed!    [![Quality Gate passed](https://camo.githubusercontent.com/e4a90cf346b46d44c5652111d68603714bfb7693043d07a95992de3a30bfce04/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f7061737365642d313670782e706e67)](https://sonarcloud.io/dashboard?id=FakeDevelopers_BidderBidder_IOS&pullRequest=6)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=6&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=6&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=6&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=6&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=6&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=6&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=FakeDevelopers_BidderBidder_IOS&pullRequest=6&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=FakeDevelopers_BidderBidder_IOS&pullRequest=6&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=FakeDevelopers_BidderBidder_IOS&pullRequest=6&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=6&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=6&resolved=false&types=CODE_SMELL) [49 Code Smells](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=6&resolved=false&types=CODE_SMELL)
> 
> [![No Coverage information](https://camo.githubusercontent.com/86785eaa572e061f5ecb3f8bf1cbb7b8eca44925083f92d067805b4362cead0c/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f4e6f436f766572616765496e666f2d313670782e706e67)](https://sonarcloud.io/component_measures?id=FakeDevelopers_BidderBidder_IOS&pullRequest=6) No Coverage information [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=FakeDevelopers_BidderBidder_IOS&pullRequest=6&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=FakeDevelopers_BidderBidder_IOS&pullRequest=6&metric=new_duplicated_lines_density&view=list)

이게 무슨 냄새야

2022-05-17 03:27 UTC, SungHyunC commented on BidderBidder/LoginViewController.swift
> +        self.layer.backgroundColor = UIColor(rgb: 0x21CEFF).cgColor
넵! 상수로 지정해보겠습니다

2022-05-17 03:27 UTC, SungHyunC commented on Podfile
> +  pod 'SnapKit'
이번에 다시 해보는데 SPM으로 써보겠습니다!

2022-05-17 03:28 UTC, SungHyunC commented on BidderBidder/LoginViewController.swift
>          //Navigation Bar 숨기기
주석달때 유의하겠습니다!

2022-05-17 04:45 UTC, SungHyunC commented on BidderBidder/LoginViewController.swift
> +   convenience init(red: Int, green: Int, blue: Int) {
오버플로우에 나와있는걸 긁어와서 uint8로는 어떻게해야될지 모르겠네요 ㅠㅠ

2022-05-17 04:56 UTC, SungHyunC commented on Pods/SnapKit/Source/Constraint.swift
> +public final class Constraint {
POD은 없애고 SPM으로 바꿨습니다!

2022-05-17 11:05 UTC, konempty requested changes
![Simulator Screen Shot - iPhone 13 - 2022-05-17 at 19 53 58](https://user-images.githubusercontent.com/44064530/168796392-8b02af58-d703-473d-9e98-13175fa8c54d.png)
아이폰 13에서 글자가 짤리는 문제가 있고

https://user-images.githubusercontent.com/44064530/168796823-f6f8dbcb-b8cf-475f-82cc-32abc9549c1e.mp4
비밀번호를 입력하면 앱이 꺼지는 문제가 있네요 ㅠㅠㅠ


[error.txt](https://github.com/FakeDevelopers/BidderBidder_IOS/files/8707646/error.txt)
에러 로그도 첨부해둘게요

조금만더 고생해주세요!

2022-05-17 11:05 UTC, konempty commented on BidderBidder/LoginViewController.swift
> +    let skyBlueColor = UIColor(rgb: 0x21CEFF)
let skyBlueColor=UIColor(rgb: 0x21CEFF).cgColor 이렇개 하면
62,63 라인에서 skyBlueColor.cgColor 뒤에 cgColor를 땔수 있지않을까요?

2022-05-17 11:05 UTC, konempty commented on BidderBidder/LoginViewController.swift
> +   convenience init(red: Int, green: Int, blue: Int) {
extension UIColor {
        convenience init(red: UInt8, green: UInt8, blue: UInt8) {
            self.init(red: CGFloat(red) / 255.0, green: CGFloat(green) / 255.0, blue: CGFloat(blue) / 255.0, alpha: 1.0)
        }

        convenience init(rgb: Int) {
            self.init(
                red: UInt8((rgb >> 16) & 0xFF),
                green: UInt8((rgb >> 8) & 0xFF),
                 blue: UInt8(rgb & 0xFF)
                )
          }
      }

이렇게 할수 있었을것 같은데 만들고 보니 예쁘지 않네요ㅋㅋㅋㅋ 이건 둘중 예쁘다 생각하시는거 적용해보시면 될것 같아요

2022-05-17 16:15 UTC, minseonglove requested changes
엗헴

2022-05-17 16:15 UTC, minseonglove commented on BidderBidder/LoginViewController.swift
> +    let skyBlueColor = UIColor(rgb: 0x21CEFF)
퍼스널 컬러는 앱의 모든 곳에 사용될 것이야
따로 컬러만 관리하는 클래스를 하나 만들어서 static let으로 관리하는건 어떨까

2022-05-18 00:41 UTC, SungHyunC commented on BidderBidder/LoginViewController.swift
> +    let skyBlueColor = UIColor(rgb: 0x21CEFF)
오우 바로 수정했습니다 왕따봉

2022-05-18 00:43 UTC, SungHyunC commented on BidderBidder/LoginViewController.swift
> +   convenience init(red: Int, green: Int, blue: Int) {
전 코드 보다는 짧아서 이게 더 좋은 것 같습니다! 이걸로 수정할게요!!

2022-05-18 00:55 UTC, SungHyunC commented on BidderBidder/LoginViewController.swift
> +    let skyBlueColor = UIColor(rgb: 0x21CEFF)
extension 쪽으로 옮겨 봤는데 이건 어떤가요?

2022-05-18 03:20 UTC, minseonglove commented on BidderBidder/LoginViewController.swift
> +extension UIColor {
컬러를 가져오는게 Login에서만 사용하는 것이 아니고 앱 전체에서 사용할 것이 잖니
그래서 LoginViewController 안에 정의하는 것 보다 따로 컬러 관리만 하는 파일을 하나 더 만들어서 거기다 작성하는게 좋아 보인다~ 는 말이였어

2022-05-18 09:14 UTC, minseonglove approved these changes
짱

2022-05-19 09:20 UTC, konempty requested changes
<img width="1429" alt="스크린샷 2022-05-19 오후 6 16 34" src="https://user-images.githubusercontent.com/44064530/169259235-0cd2f5c3-1076-439e-9c36-978a3f8bf831.png">
UI를 확인 할때는 모든 기기에서 테스트 해보면 좋겠지만 여의치 않으면 최소한 기본형, Max, mini, se 이 4개의 기기에서 모두 확인을 해봐야 해요ㅋㅋㅋㅋ 위 사진과 같이 무너지는 경우가 많거든요ㅋㅋㅋㅋ
조금만더 수정 부탁 드릴게요

2022-05-20 05:55 UTC, konempty approved these changes
크흐 고생하셨습니다! 머지하셔도 좋을듯 합니다.

2022-05-20 06:05 UTC, merged