Feature/bdbd 223
FakeDevelopers/BidderBidder_IOS pull request #8
Opened 2022-05-23 12:01 UTC by SungHyunC

### 개요
회원가입 화면 UI 제작
### 변경사항
회원가입 화면 UI 제작 및 화면 간단하게 연결
### 관련 지라 및 위키 링크
[BDBD-223](https://fake-developers.atlassian.net/jira/software/projects/BDBD/boards/10?selectedIssue=BDBD-223)
### 리뷰어에게 하고 싶은 말
약관동의 UI는 추후 추가하겠습니다. 화면 연결은 일단 간단하게만 연결했습니다.

2022-05-23 12:14 UTC, SungHyunC commented
# 각 기종별 UI 사진입니다.
<img width="200" alt="스크린샷 2022-05-23 오후 7 17 27" src="https://user-images.githubusercontent.com/41741563/169816544-028afb2f-fa59-4c09-92d7-546900eef797.png"> <img width="200" alt="스크린샷 2022-05-23 오후 7 17 30" src="https://user-images.githubusercontent.com/41741563/169816562-f9379320-4aea-4c81-b6b9-f0dfaf50d253.png"><img width="200" alt="스크린샷 2022-05-23 오후 7 17 33" src="https://user-images.githubusercontent.com/41741563/169816569-7e86b6a8-51da-4866-99d4-b8279dc244ae.png">
<img width="200" alt="스크린샷 2022-05-23 오후 7 18 22" src="https://user-images.githubusercontent.com/41741563/169816575-0bf7359c-a020-4780-afc3-834dc5cc8d99.png"><img width="200" alt="스크린샷 2022-05-23 오후 7 18 25" src="https://user-images.githubusercontent.com/41741563/169816577-8566801b-6a69-4ada-9179-d794c03edeeb.png"><img width="200" alt="스크린샷 2022-05-23 오후 7 18 27" src="https://user-images.githubusercontent.com/41741563/169816581-ccef5c6c-59b2-48ed-94a0-ef8401147ecc.png">
<img width="200" alt="스크린샷 2022-05-23 오후 7 18 56" src="https://user-images.githubusercontent.com/41741563/169816588-a87aa606-77e8-48a0-b430-96ae68c42b97.png"><img width="200" alt="스크린샷 2022-05-23 오후 7 18 58" src="https://user-images.githubusercontent.com/41741563/169816591-82441c92-5a67-475e-94b0-feb882a7f7fd.png"><img width="200" alt="스크린샷 2022-05-23 오후 7 19 00" src="https://user-images.githubusercontent.com/41741563/169816593-dd39b557-9918-42a8-b3d9-b2b47757081a.png">
<img width="200" alt="스크린샷 2022-05-23 오후 7 19 32" src="https://user-images.githubusercontent.com/41741563/169816598-d3f29c73-c5b5-4fb6-afaa-772390a6a002.png"><img width="200" alt="스크린샷 2022-05-23 오후 7 19 34" src="https://user-images.githubusercontent.com/41741563/169816599-7d0f3197-cfd1-4894-8eab-f0c8d3e4476e.png"><img width="200" alt="스크린샷 2022-05-23 오후 7 19 37" src="https://user-images.githubusercontent.com/41741563/169816604-c7ee3deb-2f5e-443b-9a54-7886a8b2c772.png">

2022-05-23 12:29 UTC, konempty approved these changes
크흐 고생하셨습니다 👍  리뷰드리고 싶은건 크게 3개 있네요
1. [여기](https://github.com/FakeDevelopers/BidderBidder_IOS/pull/4#pullrequestreview-937245821) 에 리뷰된 글머리 기호를 붙혀주시면 좋을것 같아요!
2. PR 제목이 설정이 안된것 같아요! Feature/bdbd 223 는 좋은 제목 같지는 않네요ㅠㅠ
3. 휴대폰 인증시에는 휴대번호 입력후 인증 버튼을 누르면 그때 인증번호 입력 창이 뜨면 좋을것 같아요! 지금은 단순히 UI 생김새만 잡아 놓는 과정이라 이 부분은 당장 적용될 필요는 없지만 추후에는 적용 부탁 드릴게요!
저는 머지 승인 하겠습니다!

2022-05-23 12:54 UTC, minseonglove requested changes
중복확인 버튼, 인증 버튼, 재발송 버튼
텍스트 입력칸을 기준으로 배치하십시오

2022-05-24 04:18 UTC, SungHyunC commented
<img width="1440" alt="스크린샷 2022-05-24 오후 1 17 39" src="https://user-images.githubusercontent.com/41741563/169947967-d3de65ce-12f1-4a07-96fc-a3a73c5ad05f.png">
<img width="1440" alt="스크린샷 2022-05-24 오후 1 17 32" src="https://user-images.githubusercontent.com/41741563/169947980-d34c1eed-c1f8-4f92-b71f-0b5ed02ea40a.png">
<img width="1440" alt="스크린샷 2022-05-24 오후 1 17 22" src="https://user-images.githubusercontent.com/41741563/169947984-dd55ed0c-a3dc-4c02-9f49-eaf179a5492c.png">

2022-05-24 04:24 UTC, minseonglove approved these changes
짱

2022-05-24 04:24 UTC, merged