FEAT : 메인화면 만들기
FakeDevelopers/BidderBidder_IOS pull request #9
Opened 2022-07-07 05:13 UTC by SungHyunC

### 개요
- 메인화면 만들기
### 변경사항
- 메인화면 만들기 (api 연결, 무한스크롤 제작 등)
### 관련 지라 및 위키 링크
- [BDBD-255](https://fake-developers.atlassian.net/jira/software/projects/BDBD/boards/10?selectedIssue=BDBD-255)
### 리뷰어에게 하고 싶은 말
- title 부분은 아직 미완성입니다.
- Refresh 부분 확인부탁드립니다!

2022-07-08 11:46 UTC, konempty commented
> Kudos, SonarCloud Quality Gate passed!    [![Quality Gate passed](https://camo.githubusercontent.com/e4a90cf346b46d44c5652111d68603714bfb7693043d07a95992de3a30bfce04/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f7061737365642d313670782e706e67)](https://sonarcloud.io/dashboard?id=FakeDevelopers_BidderBidder_IOS&pullRequest=9)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=9&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=9&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=9&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=9&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=9&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=9&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=FakeDevelopers_BidderBidder_IOS&pullRequest=9&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=FakeDevelopers_BidderBidder_IOS&pullRequest=9&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=FakeDevelopers_BidderBidder_IOS&pullRequest=9&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=9&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=9&resolved=false&types=CODE_SMELL) [4 Code Smells](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_IOS&pullRequest=9&resolved=false&types=CODE_SMELL)
> 
> [![No Coverage information](https://camo.githubusercontent.com/86785eaa572e061f5ecb3f8bf1cbb7b8eca44925083f92d067805b4362cead0c/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f4e6f436f766572616765496e666f2d313670782e706e67)](https://sonarcloud.io/component_measures?id=FakeDevelopers_BidderBidder_IOS&pullRequest=9) No Coverage information [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=FakeDevelopers_BidderBidder_IOS&pullRequest=9&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=FakeDevelopers_BidderBidder_IOS&pullRequest=9&metric=new_duplicated_lines_density&view=list)

코드스멜 수정부탁드려요!

2022-07-08 11:54 UTC, konempty commented
PR명은 FEAT : BDBD-255 메인화면 만들기 로 되어야 할것 같아요!

2022-07-08 12:01 UTC, konempty requested changes
크흐 고생하셨습니다! 리뷰 확인해서 조금만더 고생 부탁드릴게요!
그리고 사진 리소스들이 필요이상으로 고화질이던데 아무리 테스트 리소스여도 저렇게 고화질의 리소스는 안들어 가는게 좋을것 같아요!

2022-07-08 12:01 UTC, konempty commented on BidderBidder/Cell/ProductViewCell.swift
> +extension UIImageView {
제가 보기엔 이 extension은 여기 클래스 말고 다른곳에서 쓰일것 같은데 이 파일에 넣어두는건 좋지않을것 같아요!

2022-07-08 12:01 UTC, konempty commented on BidderBidder/Cell/ProductViewCell.swift
> +        thumbnail.downloaded(from: "http://bidderbidderapi.kro.kr:8080"+product.thumbnail)
URL은 언제 변경될지 모르기때문에 프로그램 전역에서 사용할수있는 상수로 정의하시는게 좋을것 같아요!
그리고 8080포트는 sandbox이고 80포트가 real phase이기 때문에 그것도 생각하시면서 설정해주세요!

2022-07-08 12:01 UTC, konempty commented on BidderBidder/Controller/EnterLoginViewController.swift
> +    }
이 내용도 이 파일에 남아있기에는 역할이 안 맞는것 같아요! 이런 전역적으로 사용되는 extension들은 별도의 파일에 모아두면 어떨까요?

2022-07-08 12:01 UTC, konempty commented on BidderBidder/Controller/EnterLoginViewController.swift
> +
파일 끝에 불필요한 개행이 너무 많은것 같아요!

2022-07-08 12:01 UTC, konempty commented on BidderBidder/Controller/MainViewController.swift
> +    var checkListCount: Int = 20
이건 val이어도 되지않을까요?

2022-07-08 12:01 UTC, konempty commented on BidderBidder/Controller/MainViewController.swift
> +
불필요한 개행이... ㅎㅎ

2022-07-10 08:24 UTC, Dorii0513 commented
성현님 고생하셨습니다 :)
아직 제가 아는 부분이 없어서 리뷰 드리기 부족하지만,,, 열심히 공부해서 언젠가 리뷰 드릴 수 있도록 하겠습니다!!

2022-07-10 15:59 UTC, Dorii0513 reviewed
성현님 고생하셨습니다 :)
처음에 제가 리뷰를 잘못 올려서 지우고 다시 올리게 되었습니다 ㅠㅠ
아직 제가 아는 부분이 없어서 리뷰 드리기 부족하지만,,, 열심히 공부해서 언젠가 리뷰 드릴 수 있도록 하겠습니다!

2022-07-11 13:06 UTC, minseonglove reviewed
이미지 리소스가 여러개 있는데 이건 어디 쓰는거야?

2022-07-11 13:06 UTC, minseonglove commented on BidderBidder/Controller/MainViewController.swift
> +        let contentHeight = scrollView.contentSize.height - 800
이 800은 따로 상수로 빼두는게 보기 좋아뵈

2022-07-11 13:23 UTC, konempty commented on BidderBidder/Controller/MainViewController.swift
> +        let contentHeight = scrollView.contentSize.height - 800
엇 지금 봤는데 800이란 숫자는 기기마다 비율이 다를텐데 괜찮은걸까요??

2022-07-11 13:25 UTC, minseonglove commented on BidderBidder/Controller/MainViewController.swift
> +        let offsetY = scrollView.contentOffset.y
offsetY대신 scrollView.contentOffset.y을 그대로 쓰는것도 좋아뵈

2022-07-11 13:25 UTC, minseonglove commented on BidderBidder/Controller/MainViewController.swift
> +            if offsetY > contentHeight - scrollView.frame.height {
이 두 개는 하나로 합쳐도 되겠다

2022-07-11 13:31 UTC, minseonglove commented on BidderBidder/Controller/MainViewController.swift
> +    var checkNum: Int = 0
checkNum 상태가 0 아님 1인거 같은데 Boolean으로 처리하는게 더 이쁘지 않을가

2022-07-12 10:30 UTC, SungHyunC commented on BidderBidder/Cell/ProductViewCell.swift
> +extension UIImageView {
SupportingFiles에 따로 넣어놓았습니다

2022-07-12 10:39 UTC, SungHyunC commented on BidderBidder/Controller/MainViewController.swift
> +    var checkListCount: Int = 20
이거는 왜 val로 하는걸 추천하나요?

2022-07-12 10:43 UTC, SungHyunC commented on BidderBidder/Controller/MainViewController.swift
> +        let contentHeight = scrollView.contentSize.height - 800
내려갈때 일정 크기만 내려가게 되면 끊김없이 상품들이 불러올것같아서 이렇게 해뒀습니다

2022-07-12 10:55 UTC, SungHyunC commented on BidderBidder/Controller/MainViewController.swift
> +    var checkNum: Int = 0
이건... 잠시... 보류.,..

2022-07-12 11:07 UTC, SungHyunC commented on BidderBidder/Controller/MainViewController.swift
> +        let contentHeight = scrollView.contentSize.height - 800
사진 리소스들은 잠시 테스트용이라 다 지워놓았습니다.

2022-07-12 11:10 UTC, SungHyunC commented on BidderBidder/Controller/MainViewController.swift
> +    var checkNum: Int = 0
Boolean으로 바꿔놓았습니다!

2022-07-12 11:14 UTC, minseonglove commented on BidderBidder/Controller/MainViewController.swift
> +    var checkListCount: Int = 20
> 이거는 왜 val로 하는걸 추천하나요?

let let

2022-07-12 11:19 UTC, minseonglove approved these changes
좋다

2022-07-12 11:28 UTC, konempty requested changes
아주 쪼금만더 고생부탁드릴게요! ㅎㅎ

2022-07-12 11:28 UTC, konempty commented on BidderBidder/Controller/MainViewController.swift
> +        if checkBool == true && scrollView.contentOffset.y > contentHeight - scrollView.frame.height {
checkBool == true 이부분은 checkBool로 줄일수 있지 않을까요?

2022-07-12 11:28 UTC, konempty commented on BidderBidder/Controller/MainViewController.swift
> +        sendRestRequest(url:"http://bidderbidderapi.kro.kr:8080/product/getInfiniteProductList", params:["searchWord":"","listCount":listCount,"startNumber":startNumber,"serachType":2]  , isPost: fal
여기 있는 URL도 정리할수 있지않을까요?

2022-07-12 11:28 UTC, konempty commented on BidderBidder/Controller/MainViewController.swift
> +    var listInterval: Int = 800
이값은 불변하지 않나요?

2022-07-12 11:28 UTC, konempty commented on BidderBidder/Controller/MainViewController.swift
> +        let contentHeight = scrollView.contentSize.height - CGFloat(listInterval)
listInterval의 자료형을 CGFloat로 정했다면 CGFloat(listInterval)이코드는 간단해질수 있을것 같아요!

2022-07-12 11:28 UTC, konempty commented on BidderBidder/Cell/ProductViewCell.swift
> +    static let domainURL = "http://bidderbidderapi.kro.kr"
저는 보통 이런 전역 상수는 Constant라는 파일을 만들어서 그 안에서 관리해요!ㅋㅋㅋㅋ

2022-07-12 12:43 UTC, konempty approved these changes
고생하셨습니다 👍

2022-07-12 12:50 UTC, merged